#!/usr/bin/env bats
load test_helper/common

setup() {
  TEST_DIR="$(mktemp -d)"
  TEST_BINDLE="$TEST_DIR/config"
  mkdir -p "$TEST_BINDLE/modules"
  mkdir -p "$TEST_BINDLE/profiles"
  # Isolate from real system
  NOMADIC_DIR="$TEST_DIR/state"
  ORIG_HOME="$HOME"
  HOME="$TEST_DIR/home"
  mkdir -p "$HOME"
  # Stub out package manager so tests don't hit the real one
  detect_pkg_manager() { return 1; }
  export -f detect_pkg_manager
}

teardown() {
  HOME="$ORIG_HOME"
  unset -f detect_pkg_manager
  rm -rf "$TEST_DIR"
}

@test "apply: generates rc file from module bash configs" {
  create_module "alpha"
  printf 'export ALPHA="yes"\n' >"$TEST_BINDLE/modules/alpha/bash"
  create_module "beta"
  printf 'export BETA="yes"\n' >"$TEST_BINDLE/modules/beta/bash"

  cmd_apply "$TEST_BINDLE"

  [ -f "$NOMADIC_DIR/rc.bash" ]
  grep -q 'export ALPHA="yes"' "$NOMADIC_DIR/rc.bash"
  grep -q 'export BETA="yes"' "$NOMADIC_DIR/rc.bash"
  grep -q 'Generated by nomadic' "$NOMADIC_DIR/rc.bash"
}

@test "apply: creates symlinks from links files" {
  create_module "mymod"
  echo "dotfile content" >"$TEST_BINDLE/modules/mymod/myrc"
  printf 'myrc %s/.myrc\n' "$HOME" >"$TEST_BINDLE/modules/mymod/links"

  cmd_apply "$TEST_BINDLE"

  [ -L "$HOME/.myrc" ]
  [ "$(readlink "$HOME/.myrc")" = "$TEST_BINDLE/modules/mymod/myrc" ]
}

@test "apply: runs setup scripts" {
  create_module "mymod"
  printf 'touch "%s/setup_ran"\n' "$TEST_DIR" >"$TEST_BINDLE/modules/mymod/setup"

  cmd_apply "$TEST_BINDLE"

  [ -f "$TEST_DIR/setup_ran" ]
}

@test "apply: filters modules by OS" {
  create_module "universal"
  printf 'export UNI="yes"\n' >"$TEST_BINDLE/modules/universal/bash"
  create_module "wrong-os" "os: fakeos"
  printf 'export WRONG="yes"\n' >"$TEST_BINDLE/modules/wrong-os/bash"

  cmd_apply "$TEST_BINDLE"

  [ -f "$NOMADIC_DIR/rc.bash" ]
  grep -q 'export UNI="yes"' "$NOMADIC_DIR/rc.bash"
  ! grep -q 'export WRONG="yes"' "$NOMADIC_DIR/rc.bash"
}

@test "apply: preserves dependency order in rc file" {
  create_module "first"
  printf 'export FIRST="yes"\n' >"$TEST_BINDLE/modules/first/bash"
  create_module "second" "after: first"
  printf 'export SECOND="yes"\n' >"$TEST_BINDLE/modules/second/bash"
  create_module "third" "after: second"
  printf 'export THIRD="yes"\n' >"$TEST_BINDLE/modules/third/bash"

  cmd_apply "$TEST_BINDLE"

  # Check that FIRST appears before SECOND, and SECOND before THIRD
  first_line="$(grep -n 'FIRST' "$NOMADIC_DIR/rc.bash" | head -1 | cut -d: -f1)"
  second_line="$(grep -n 'SECOND' "$NOMADIC_DIR/rc.bash" | head -1 | cut -d: -f1)"
  third_line="$(grep -n 'THIRD' "$NOMADIC_DIR/rc.bash" | head -1 | cut -d: -f1)"
  [ "$first_line" -lt "$second_line" ]
  [ "$second_line" -lt "$third_line" ]
}

@test "apply: infects shell rc file" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_BINDLE/modules/mymod/bash"

  cmd_apply "$TEST_BINDLE"

  [ -f "$HOME/.bashrc" ]
  grep -q 'NOMADIC_MANAGED' "$HOME/.bashrc"
}

@test "apply: exits cleanly without unbound variable errors" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_BINDLE/modules/mymod/bash"

  run env HOME="$HOME" NOMADIC_DIR="$NOMADIC_DIR" \
    "$NOMADIC_ROOT/nomadic" apply -P "$TEST_BINDLE"
  [ "$status" -eq 0 ]
  [[ "$output" != *"unbound variable"* ]]
}

@test "apply: --help shows usage" {
  run main apply --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"nomadic"* ]]
}

@test "apply: rejects unknown long flag" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_BINDLE/modules/mymod/bash"

  run cmd_apply --bogus "$TEST_BINDLE"
  [ "$status" -ne 0 ]
  [[ "$output" == *"Unknown option: --bogus"* ]]
}

@test "apply: rejects unknown short flag" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_BINDLE/modules/mymod/bash"

  run cmd_apply -x "$TEST_BINDLE"
  [ "$status" -ne 0 ]
  [[ "$output" == *"Unknown option: -x"* ]]
}

@test "apply: combined short flags work" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_BINDLE/modules/mymod/bash"

  cmd_apply -fPL "$TEST_BINDLE"

  [ -f "$NOMADIC_DIR/rc.bash" ]
  grep -q 'export FOO="bar"' "$NOMADIC_DIR/rc.bash"
}

@test "apply: combined flags reject unknown flag" {
  run cmd_apply -fPx "$TEST_BINDLE"
  [ "$status" -ne 0 ]
  [[ "$output" == *"Unknown option: -x"* ]]
}

@test "apply: remembers config path" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_BINDLE/modules/mymod/bash"

  cmd_apply "$TEST_BINDLE"

  [ -f "$NOMADIC_DIR/state/bindle-path" ]
  grep -q "$TEST_BINDLE" "$NOMADIC_DIR/state/bindle-path"
}
