#!/usr/bin/env bats
load test_helper/common

setup() {
  TEST_DIR="$(mktemp -d)"
  TEST_CONFIG="$TEST_DIR/config"
  mkdir -p "$TEST_CONFIG/modules"
  mkdir -p "$TEST_CONFIG/profiles"
  # Isolate from real system
  NOMAD_STATE_DIR="$TEST_DIR/state"
  ORIG_HOME="$HOME"
  HOME="$TEST_DIR/home"
  mkdir -p "$HOME"
}

teardown() {
  HOME="$ORIG_HOME"
  rm -rf "$TEST_DIR"
}

@test "apply: generates rc file from module bash configs" {
  create_module "alpha"
  printf 'export ALPHA="yes"\n' >"$TEST_CONFIG/modules/alpha/bash"
  create_module "beta"
  printf 'export BETA="yes"\n' >"$TEST_CONFIG/modules/beta/bash"

  cmd_apply "$TEST_CONFIG"

  [ -f "$NOMAD_STATE_DIR/config.bash" ]
  grep -q 'export ALPHA="yes"' "$NOMAD_STATE_DIR/config.bash"
  grep -q 'export BETA="yes"' "$NOMAD_STATE_DIR/config.bash"
  grep -q 'Generated by nomad' "$NOMAD_STATE_DIR/config.bash"
}

@test "apply: creates symlinks from links files" {
  create_module "mymod"
  echo "dotfile content" >"$TEST_CONFIG/modules/mymod/myrc"
  printf 'myrc %s/.myrc\n' "$HOME" >"$TEST_CONFIG/modules/mymod/links"

  cmd_apply "$TEST_CONFIG"

  [ -L "$HOME/.myrc" ]
  [ "$(readlink "$HOME/.myrc")" = "$TEST_CONFIG/modules/mymod/myrc" ]
}

@test "apply: runs setup scripts" {
  create_module "mymod"
  printf 'touch "%s/setup_ran"\n' "$TEST_DIR" >"$TEST_CONFIG/modules/mymod/setup"

  cmd_apply "$TEST_CONFIG"

  [ -f "$TEST_DIR/setup_ran" ]
}

@test "apply: filters modules by OS" {
  create_module "universal"
  printf 'export UNI="yes"\n' >"$TEST_CONFIG/modules/universal/bash"
  create_module "wrong-os" "os: fakeos"
  printf 'export WRONG="yes"\n' >"$TEST_CONFIG/modules/wrong-os/bash"

  cmd_apply "$TEST_CONFIG"

  [ -f "$NOMAD_STATE_DIR/config.bash" ]
  grep -q 'export UNI="yes"' "$NOMAD_STATE_DIR/config.bash"
  ! grep -q 'export WRONG="yes"' "$NOMAD_STATE_DIR/config.bash"
}

@test "apply: skips modules with missing cmd requirement" {
  create_module "good"
  printf 'export GOOD="yes"\n' >"$TEST_CONFIG/modules/good/bash"
  create_module "needs-missing" "cmd: nonexistent_command_xyz"
  printf 'export BAD="yes"\n' >"$TEST_CONFIG/modules/needs-missing/bash"

  cmd_apply "$TEST_CONFIG"

  [ -f "$NOMAD_STATE_DIR/config.bash" ]
  grep -q 'export GOOD="yes"' "$NOMAD_STATE_DIR/config.bash"
  ! grep -q 'export BAD="yes"' "$NOMAD_STATE_DIR/config.bash"
}

@test "apply: preserves dependency order in rc file" {
  create_module "first"
  printf 'export FIRST="yes"\n' >"$TEST_CONFIG/modules/first/bash"
  create_module "second" "after: first"
  printf 'export SECOND="yes"\n' >"$TEST_CONFIG/modules/second/bash"
  create_module "third" "after: second"
  printf 'export THIRD="yes"\n' >"$TEST_CONFIG/modules/third/bash"

  cmd_apply "$TEST_CONFIG"

  # Check that FIRST appears before SECOND, and SECOND before THIRD
  first_line="$(grep -n 'FIRST' "$NOMAD_STATE_DIR/config.bash" | head -1 | cut -d: -f1)"
  second_line="$(grep -n 'SECOND' "$NOMAD_STATE_DIR/config.bash" | head -1 | cut -d: -f1)"
  third_line="$(grep -n 'THIRD' "$NOMAD_STATE_DIR/config.bash" | head -1 | cut -d: -f1)"
  [ "$first_line" -lt "$second_line" ]
  [ "$second_line" -lt "$third_line" ]
}

@test "apply: infects shell rc file" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_CONFIG/modules/mymod/bash"

  cmd_apply "$TEST_CONFIG"

  [ -f "$HOME/.bashrc" ]
  grep -q 'NOMAD_MANAGED' "$HOME/.bashrc"
}

@test "apply: exits cleanly without unbound variable errors" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_CONFIG/modules/mymod/bash"

  run env HOME="$HOME" NOMAD_STATE_DIR="$NOMAD_STATE_DIR" \
    "$NOMAD_ROOT/nomad" apply "$TEST_CONFIG"
  [ "$status" -eq 0 ]
  [[ "$output" != *"unbound variable"* ]]
}

@test "apply: remembers config path" {
  create_module "mymod"
  printf 'export FOO="bar"\n' >"$TEST_CONFIG/modules/mymod/bash"

  cmd_apply "$TEST_CONFIG"

  [ -f "$NOMAD_STATE_DIR/state/config-path" ]
  grep -q "$TEST_CONFIG" "$NOMAD_STATE_DIR/state/config-path"
}
