#!/usr/bin/env bats
load test_helper/common

setup() {
  TEST_DIR="$(mktemp -d)"
  TEST_CONFIG="$TEST_DIR/config"
  mkdir -p "$TEST_CONFIG/modules"
  mkdir -p "$TEST_CONFIG/profiles"
  # Override state dir and HOME for isolated testing
  NOMADIC_DIR="$TEST_DIR/state"
  ORIG_HOME="$HOME"
  HOME="$TEST_DIR/home"
  mkdir -p "$HOME"
}

teardown() {
  HOME="$ORIG_HOME"
  rm -rf "$TEST_DIR"
}

@test "generate_rc: writes content to correct path" {
  echo "export FOO=bar" | generate_rc "bash"
  [ -f "$NOMADIC_DIR/config.bash" ]
  grep -q 'export FOO=bar' "$NOMADIC_DIR/config.bash"
}

@test "generate_rc: creates state directory if needed" {
  [ ! -d "$NOMADIC_DIR" ]
  echo "content" | generate_rc "bash"
  [ -d "$NOMADIC_DIR" ]
}

@test "generate_rc: adds header comment" {
  echo "content" | generate_rc "bash"
  head -1 "$NOMADIC_DIR/config.bash" | grep -q 'Generated by nomadic'
}

@test "infect_rc: adds source line to bashrc" {
  infect_rc "bash"
  [ -f "$HOME/.bashrc" ]
  grep -q 'NOMADIC_MANAGED' "$HOME/.bashrc"
  grep -q "source $NOMADIC_DIR/config.bash" "$HOME/.bashrc"
}

@test "infect_rc: is idempotent" {
  infect_rc "bash"
  infect_rc "bash"
  local count
  count="$(grep -c 'NOMADIC_MANAGED' "$HOME/.bashrc")"
  [ "$count" -eq 1 ]
}

@test "infect_rc: handles missing rc file" {
  [ ! -f "$HOME/.bashrc" ]
  infect_rc "bash"
  [ -f "$HOME/.bashrc" ]
}

@test "infect_rc: works with zsh" {
  infect_rc "zsh"
  [ -f "$HOME/.zshrc" ]
  grep -q 'NOMADIC_MANAGED' "$HOME/.zshrc"
  grep -q "source $NOMADIC_DIR/config.zsh" "$HOME/.zshrc"
}

@test "infect_rc: preserves existing rc file content" {
  printf 'existing_line\n' >"$HOME/.bashrc"
  infect_rc "bash"
  grep -q 'existing_line' "$HOME/.bashrc"
  grep -q 'NOMADIC_MANAGED' "$HOME/.bashrc"
}

@test "infect_rc: creates bash_profile for login shells" {
  infect_rc "bash"
  [ -f "$HOME/.bash_profile" ]
  grep -q 'NOMADIC_MANAGED' "$HOME/.bash_profile"
  grep -q "source $NOMADIC_DIR/config.bash" "$HOME/.bash_profile"
}

@test "infect_rc: infects existing bash_profile" {
  printf 'existing_profile\n' >"$HOME/.bash_profile"
  infect_rc "bash"
  grep -q 'existing_profile' "$HOME/.bash_profile"
  grep -q 'NOMADIC_MANAGED' "$HOME/.bash_profile"
}

@test "infect_rc: bash_profile is idempotent" {
  infect_rc "bash"
  infect_rc "bash"
  local count
  count="$(grep -c 'NOMADIC_MANAGED' "$HOME/.bash_profile")"
  [ "$count" -eq 1 ]
}

@test "infect_rc: does not create bash_profile for zsh" {
  infect_rc "zsh"
  [ ! -f "$HOME/.bash_profile" ]
}

@test "generate_rc: includes update check hook" {
  echo "content" | generate_rc "bash"
  grep -q '_nomadic_update_check' "$NOMADIC_DIR/config.bash"
}

@test "generate_rc: update hook embeds current version" {
  echo "content" | generate_rc "bash"
  grep -q "local current=\"$NOMADIC_VERSION\"" "$NOMADIC_DIR/config.bash"
}

@test "generate_rc: update hook shows and clears notice file" {
  echo "content" | generate_rc "bash"
  mkdir -p "$NOMADIC_DIR/state"
  echo '[nomadic] Update available: v0.3.0 -> v0.4.0 (run "nomadic update")' \
    >"$NOMADIC_DIR/state/update-notice"

  # Source the generated rc and capture output
  result="$(bash -c "source '$NOMADIC_DIR/config.bash'" 2>/dev/null)"
  [[ "$result" == *"Update available"* ]]
  [ ! -f "$NOMADIC_DIR/state/update-notice" ]
}

@test "generate_rc: update hook skips check within 24h" {
  echo "content" | generate_rc "bash"
  mkdir -p "$NOMADIC_DIR/state"
  # Stamp is recent - should not spawn a background check
  date +%s >"$NOMADIC_DIR/state/update-stamp"

  bash -c "source '$NOMADIC_DIR/config.bash'" 2>/dev/null
  # No notice file should be created (no check was run)
  [ ! -f "$NOMADIC_DIR/state/update-notice" ]
}
