#!/usr/bin/env bats
load test_helper/common

setup() {
  TEST_DIR="$(mktemp -d)"
  TEST_CONFIG="$TEST_DIR/config"
  mkdir -p "$TEST_CONFIG/modules"
  mkdir -p "$TEST_CONFIG/profiles"
  # Override state dir and HOME for isolated testing
  NOMAD_STATE_DIR="$TEST_DIR/state"
  ORIG_HOME="$HOME"
  HOME="$TEST_DIR/home"
  mkdir -p "$HOME"
}

teardown() {
  HOME="$ORIG_HOME"
  rm -rf "$TEST_DIR"
}

@test "generate_rc: writes content to correct path" {
  echo "export FOO=bar" | generate_rc "bash"
  [ -f "$NOMAD_STATE_DIR/config.bash" ]
  grep -q 'export FOO=bar' "$NOMAD_STATE_DIR/config.bash"
}

@test "generate_rc: creates state directory if needed" {
  [ ! -d "$NOMAD_STATE_DIR" ]
  echo "content" | generate_rc "bash"
  [ -d "$NOMAD_STATE_DIR" ]
}

@test "generate_rc: adds header comment" {
  echo "content" | generate_rc "bash"
  head -1 "$NOMAD_STATE_DIR/config.bash" | grep -q 'Generated by nomad'
}

@test "infect_rc: adds source line to bashrc" {
  infect_rc "bash"
  [ -f "$HOME/.bashrc" ]
  grep -q 'NOMAD_MANAGED' "$HOME/.bashrc"
  grep -q "source $NOMAD_STATE_DIR/config.bash" "$HOME/.bashrc"
}

@test "infect_rc: is idempotent" {
  infect_rc "bash"
  infect_rc "bash"
  local count
  count="$(grep -c 'NOMAD_MANAGED' "$HOME/.bashrc")"
  [ "$count" -eq 1 ]
}

@test "infect_rc: handles missing rc file" {
  [ ! -f "$HOME/.bashrc" ]
  infect_rc "bash"
  [ -f "$HOME/.bashrc" ]
}

@test "infect_rc: works with zsh" {
  infect_rc "zsh"
  [ -f "$HOME/.zshrc" ]
  grep -q 'NOMAD_MANAGED' "$HOME/.zshrc"
  grep -q "source $NOMAD_STATE_DIR/config.zsh" "$HOME/.zshrc"
}

@test "infect_rc: preserves existing rc file content" {
  printf 'existing_line\n' >"$HOME/.bashrc"
  infect_rc "bash"
  grep -q 'existing_line' "$HOME/.bashrc"
  grep -q 'NOMAD_MANAGED' "$HOME/.bashrc"
}
